import Navbar from "@/components/layout/Navbar/Navbar";
import "./globals.css";
// import ThemeProviders from "@/Context/ThemeProviders";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import Footer from "@/components/layout/Footer/Footer";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <ThemeProviders> */}
        <Navbar />

        {children}
        {/* </ThemeProviders> */}

        <Footer />
      </body>
    </html>
  );
}
