import Navbar from "@/components/layout/Navbar/Navbar";
import "./globals.css";
import ThemeProviders from "@/Context/ThemeProviders";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProviders>
          <Navbar />
          {children}
        </ThemeProviders>
      </body>
    </html>
  );
}
